mkdir "$1"
cp template.cpp "$1/a.cpp"
cp template.cpp "$1/b.cpp"
cp template.cpp "$1/c.cpp"
cp template.cpp "$1/d.cpp"
cp template.cpp "$1/e.cpp"
cp template.cpp "$1/f.cpp"
# cp template.cpp "$1/g.cpp"
# cp template.cpp "$1/h.cpp"
# cp template.cpp "$1/i.cpp"
# cp template.cpp "$1/j.cpp"
# cp template.cpp "$1/k.cpp"
# cp template.cpp "$1/l.cpp"
# cp template.cpp "$1/m.cpp"
